### ISSUE TITLE
tests: cln-rpc doesn't cover all channel states

### ISSUE THREAD

**Issue by JssDWt** [breez/lspd#100]
Error during test https://github.com/breez/lspd/actions/runs/5782332133/job/15669005279 (first run)

```
goroutine 21 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/debug/stack.go:16 +0x19
github.com/breez/lntest.CheckError(0xc0004e2340, {0x1133ee0, 0xc00011ad08})
	/home/runner/go/pkg/mod/github.com/breez/lntest@v0.0.25/test_common.go:44 +0x39
github.com/breez/lntest.(*ClnNode).GetChannels(0xc0000aa300)
	/home/runner/go/pkg/mod/github.com/breez/lntest@v0.0.25/cln_node.go:584 +0x9f
github.com/breez/lspd/itest.testDynamicFeeFlow(0xc0000af680)
	/home/runner/work/lspd/lspd/itest/dynamic_fee_test.go:137 +0x1259
github.com/breez/lspd/itest.runTest(0xc0004e2340, 0x1725740, {0xf345ae?, 0x0?}, 0x1056520, 0x1056518)
	/home/runner/work/lspd/lspd/itest/lspd_test.go:89 +0x422
github.com/breez/lspd/itest.runTests.func1(0x0?)
	/home/runner/work/lspd/lspd/itest/lspd_test.go:47 +0x2d
testing.tRunner(0xc0004e2340, 0xc0000adb00)
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1629 +0x3ea
    test_common.go:45: rpc error: code = Unknown desc = Error calling method ListPeerChannels: RpcError { code: None, message: "Malformed response from lightningd: unknown variant `RCVD_REMOVE_REVOCATION`, expected one of `SENT_ADD_HTLC`, `SENT_ADD_COMMIT`, `RCVD_ADD_REVOCATION`, `RCVD_ADD_ACK_COMMIT`, `SENT_ADD_ACK_REVOCATION`, `RCVD_ADD_ACK_REVOCATION`, `RCVD_REMOVE_HTLC`, `RCVD_REMOVE_COMMIT`, `SENT_REMOVE_REVOCATION`, `SENT_REMOVE_ACK_COMMIT`, `RCVD_REMOVE_ACK_REVOCATION`" }
```

**Comment by JssDWt** [comment]
Closing due to never occurring again. Could be fixed.
