### ISSUE TITLE
tests: fix flaky test

### ISSUE THREAD

**Issue by JssDWt** [breez/lspd#101]
[test LND testOfflineNotificationZeroConfChannel](https://github.com/breez/lspd/actions/runs/5782332133/job/15669979356#logs)

```
goroutine 287 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/debug/stack.go:16 +0x19
github.com/breez/lntest.CheckError(0xc0001ca340, {0x1133ee0, 0xc000014a80})
	/home/runner/go/pkg/mod/github.com/breez/lntest@v0.0.25/test_common.go:44 +0x39
github.com/breez/lntest.(*LndNode).ConnectPeer(0xc0000eca00, {0x1146318, 0xc0001e7e00})
	/home/runner/go/pkg/mod/github.com/breez/lntest@v0.0.25/lnd_node.go:421 +0x285
github.com/breez/lspd/itest.testOfflineNotificationZeroConfChannel.func2()
	/home/runner/work/lspd/lspd/itest/notification_test.go:285 +0xaa
created by github.com/breez/lspd/itest.testOfflineNotificationZeroConfChannel
	/home/runner/work/lspd/lspd/itest/notification_test.go:281 +0xd4a
    test_common.go:45: rpc error: code = Unknown desc = already connected to peer: 038e10c282da1febc7aac2ef6e0836ebde537594c40fc0125097217dd773d013d5@127.0.0.1:45975
```

**Comment by JssDWt** [comment]
Fixed by https://github.com/breez/lspd/pull/102
