### ISSUE TITLE
test flake: unsupported curve

### ISSUE THREAD

**Issue by JssDWt** [breez/lspd#223]
https://github.com/breez/lspd/actions/runs/8953053239/job/24591134038?pr=222#step:3:299

This is the first time I've seen this error in a test. During RegisterPayment in test `testOpenZeroConfSingleHtlc`, coming from this line on the server: https://github.com/breez/lspd/blob/4611843804c17409c7eec01977d7fd745d5c1bab/cmd/lspd/channel_opener_server.go#L97

Did we generate an invalid LSP encryption key during the test?

```
2024/05/04 20:28:33 Registering payment
goroutine 22 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:16 +0x13
github.com/breez/lntest.CheckError(0xc000194000, {0x11dc8a0, 0xc000070af8})
	/home/runner/go/pkg/mod/github.com/breez/lntest@v0.0.30-0.20240324204336-6f828e9fca8f/test_common.go:44 +0x31
github.com/breez/lspd/itest.RegisterPayment({0x11f23c0, 0xc000304000}, 0xc00044b7c0?, 0x0)
	/home/runner/work/lspd/lspd/itest/lspd_node.go:401 +0x2c5
github.com/breez/lspd/itest.testOpenZeroConfSingleHtlc(0xc000696730)
	/home/runner/work/lspd/lspd/itest/intercept_zero_conf_test.go:97 +0x83f
github.com/breez/lspd/itest.runTest(0xc000194000, 0x18e9ac0, {0xfeace1?, 0x0?}, 0x10ea178, 0x10ea180)
	/home/runner/work/lspd/lspd/itest/lspd_test.go:110 +0x5e4
github.com/breez/lspd/itest.runTests.func1(0x0?)
	/home/runner/work/lspd/lspd/itest/lspd_test.go:68 +0x27
testing.tRunner(0xc000194000, 0xc0004a0780)
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 21
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:1648 +0x3ad
    test_common.go:45: rpc error: code = Unknown desc = btcec.Decrypt(04d9ee3b42ac4fcbaa9aef2[291](https://github.com/breez/lspd/actions/runs/8953053239/job/24591134038?pr=222#step:3:300)6d9d57171fef8c2dd781da79d1741c0f451889ec002209852485a4dc880dcb99a810d2a4610bf97b208b5e8bdf442ef43d2acd59fbe0b4f095d15ace39038dced6c5b70515bd5653edf5e2b898e8db0ec6c3d0927987c74f575bafe72f75a9e97815f1d970fcc0d0ace900e0d25fe04a43d3346724950ae375836eb488f96ee8f16096f776d685db4e3b1f6541882caed465fd5a2c2d0e2202bfcb7b1098015e56f68440d7df66c18fee81dade1026dfa064eb1d09e216c57c9fad32149b963130b463) error: unsupported curve
```

**Comment by JssDWt** [comment]
Haven't seen this anymore
